stages:
  - test
  - build
  - deploy
  - release

include:
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/golang/tests_with_local_dynamodb.yml'
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/golang/build_binary.yml'
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/docker/ecr.build.image.yml'
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/aws/lambda.ecr.deploy.yml'
